[package]
name = "random-name"
version = "0.1.0"
authors = ["Rainer <rainer@software-architects.at>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"] 

[features]

[dependencies]
wasm-bindgen = "0.2"
js-sys = "0.3"
conv = "0.3.3"

[profile.release]
opt-level = "s"
