spin_manifest_version = "1"
authors = ["Rainer <rainer@software-architects.at>"]
description = ""
name = "word_puzzle_spin"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "word-puzzle-spin"
source = "target/wasm32-wasi/release/word_puzzle_spin.wasm"
allowed_http_hosts = []
[component.trigger]
route = "/..."
[component.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]
