
# Calling cargo-show-asm
asm METHOD:
    echo "++++++++++++++++++++++++++++++++++"
    echo "++++++++++++++++++++++++++++++++++"
    echo "++++++++++++++++++++++++++++++++++"
    echo "++++++++++++++++++++++++++++++++++"
    echo "Smell Panty >>>>>>>>>>>>>>>>>>>>>>>"
    cargo asm yrm::w2::{{METHOD}} --rust