
# Calling cargo-show-asm
asm METHOD:
    echo "++++++++++++++++++++++++++++++++++"
    echo "++++++++++++++++++++++++++++++++++"
    echo "++++++++++++++++++++++++++++++++++"
    echo "++++++++++++++++++++++++++++++++++"
    echo "Smell Panty >>>>>>>>>>>>>>>>>>>>>>>"
    cargo asm yrm::w1::{{METHOD}} --rust